# Generated by Django 4.0.6 on 2022-07-05 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='taks',
        ),
    ]
